SimpleRotator/Models/Ad.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Query.Dynamic;

using SimpleRotator.Tools;

namespace SimpleRotator.Models
{
    public interface IAd
    {
        string Html { get; set; }
        int Rotation { get; set; }
        System.DateTime StartDate { get; set; }
        System.DateTime EndDate { get; set; }
    }

    public class Ad : IAd
    {
        public Ad(string fileContent)
        {
            // Split the file into lines
            var fileLines = fileContent.Split('\n');

            // Trim all lines, remove any comment lines TODO: handle lines less than 2 chars long
            var lines = fileLines.Select(l => l.Trim()).Where(l => l.Length > 0 && l.Left(2) != "//").ToArray();

            if (lines.Length < 4)
            {
                throw new FormatException("Input file must have at least 4 non-comment lines");
            }

            // First line is the start date
            StartDate = ParseDate(lines[0], "StartDate");

            // Second line is the end date
            EndDate = ParseDate(lines[1], "EndDate");

            // Third line is rotation
            Rotation = int.Parse(lines[2]);

            // Fourth line, and any subsequent lines, is the html
            Html = string.Join("\n", lines.Skip(3));
        }

        public string Html { get; set; }
        public int Rotation { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }

        CultureInfo enUS = new CultureInfo("en-US");

        private System.DateTime ParseDate(string txt, string paramName)
        {
            System.DateTime dt;
            if (!System.DateTime.TryParse(txt,  out dt))
            {
                throw new ArgumentException("Unable to parse " + paramName + " portion of file");
            }
            return dt;
        }
    }

    //public class DummyAd : IAd
    //{
    //    public DummyAd(string fileContent)
    //    {
    //        // Dummy Data
    //        StartDate = DateTime.MinValue;
    //        EndDate = DateTime.MaxValue;
    //        Rotation = 50;
    //        Html = "html here";
    //    }
    //
    //    public string Html { get; set; }
    //    public int Rotation { get; set; }
    //    public DateTime StartDate { get; set; }
    //    public DateTime EndDate { get; set; }
    //}
}

SimpleRotator/Models/ErrorAd.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SimpleRotator.Models
{
    //public class ErrorAd : IAd
    //{
    //    public string Html
    //    {
    //        get { return "Error occured. "; }
    //    }
    //
    //    public int Rotation
    //    {
    //        get { return 0; }
    //    }
    //
    //    public DateTime StartDate
    //    {
    //        get { return DateTime.Now; }
    //    }
    //
    //    public DateTime EndDate
    //    {
    //        get { return DateTime.Now; }
    //    }
    //}
}

SimpleRotator/Models/Zone.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using SimpleRotator.Tools;

namespace SimpleRotator.Models
{
    public class Zone
    {
        public string Name { get; set; }
        public IList<IAd> Ads { get; set; }

        public Zone(FileIO io, string directory)
        {
            Name = io.GetFolderName(directory);

            var files = io.GetFiles(directory);

            Ads = new List<IAd>(files.Count());
            foreach (var file in files)
            {
                Ads.Add(new Ad(io.ReadAllText(directory, file)));
            }
        }
    }
}

SimpleRotator/Controllers/AdController.cs
using SimpleRotator.Managers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleRotator.Controllers
{
    public class AdController : Controller
    {
        public ActionResult GetAd(string zone)
        {
            return Content(AdSelector.GetAdAsScript(Factory.GetRepo(), Factory.GetDateTime(), zone));
        }

        public ActionResult GetClientScript(string zone)
        {
            return View((object)zone);
        }

        public ActionResult ShowSchedule()
        {
            return View();
        }
    }
}

SimpleRotator/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleRotator.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

SimpleRotator/Controllers/PreviewController.cs
using SimpleRotator.Managers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleRotator.Controllers
{
    public class PreviewController : Controller
    {
        public ActionResult Index()
        {
            return View(Factory.GetRepo().Zones);
        }
    }
}

SimpleRotator/Views/Ad/GetClientScript.cshtml
@model string
@{
    string url = Request.Url.GetLeftPart(UriPartial.Authority) + Url.Action("GetAd", "Ad", new { zone = Model });
}
<!-- BEGIN Ad CODE -->
<script type="text/javascript">
    ts = String.fromCharCode(60);
    document.write(ts + 'script src="@Html.Raw(url)?r=' + Math.random() + '">' + ts + '/script>');
</script>
<!-- END Ad CODE -->

SimpleRotator/Views/Home/Index.cshtml
@{
    ViewBag.Title = "SimpleRotator";
}

<h2>SimpleRotator</h2>

SimpleRotator is an ad/banner rotator that doesn't require a database. All ads, the zones they belong to, and the properties of thier rotation, are all read from the filesystem.<br/>
<br/>
The project is free and open source. It resides at:<br/><br/>
<a href="https://github.com/NNordhaus/SimpleRotator">https://github.com/NNordhaus/SimpleRotator</a>

SimpleRotator/Views/Preview/Index.cshtml
@using SimpleRotator.Models
@model IEnumerable<Zone>

@{
    ViewBag.Title = "Preview";
}

<h2>Preview Ad Codes and ads</h2>

@foreach (Zone z in Model)
{
    string script = Html.Partial("~/Views/Ad/GetClientScript.cshtml", (object)z.Name).ToString();
    <div>
        <h2>@z.Name</h2><br />
        <textarea rows="6" cols="120">@script</textarea><br />
        @Html.Raw(script)
    </div>
}

SimpleRotator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>

<body>
    @RenderBody()
</body>
</html>